export type { Product, Category, CategoryId } from './model/types'
export { CATEGORIES } from './model/types'
export { setSelectedProduct, clearSelectedProduct } from './model/productSlice'
export { default as productReducer } from './model/productSlice'
export type { ApiProduct, ApiProductImage } from './model/apiTypes'
export { buildImageUrl } from './model/apiTypes'
export { productsApi, useLazyGetCategoryProductsQuery } from './model/productsApi'
